example:
  labels_config: 
    - Green
    - Blue
    - Another
    - New
    - Tired
  index_cols: idx
  target: text
transcripts:
  labels_config: 
    - Important
    - New Section
  index_cols: time_stamp
  target: text
video_slicing:
  labels_config: 
    - Select
    - Begin
    - End
  index_cols: time_stamp
  target: text
google_search:
  labels_config: 
    - Keep
  index_cols: idx
  target: text
  column_names:
    - Domain
    - Title
    - Snippet
  content_editable: True
  add_remove_lines: True
  search_column: Content
script_editor:
  labels_config:
    - ppt
    - vox
  index_cols: idx
  target: text
  column_names:
    - Domain
    - Title
    - Snippet
  content_editable: True
  add_remove_lines: True
  search_column: Content